;;; Automatically generated by ‘recentf’ on Thu Jun 29 10:36:41 2023.

(setq recentf-list
      '(
        "/Users/tracyfrench/dev/dotfiles/.emacs.d/init.el"
        "/Users/tracyfrench/dev/dotfiles/.emacs.d/custom.el"
        "/Users/tracyfrench/.emacs.d/init.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
