;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(empty-history extended-command-history file-name-history))
(setq file-name-history '("~/.emacs.d/init.el"))
